[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = False
addons_path = ~/code/3m/odoo_lab/odoo_16/odoo/addons
default_productivity_apps = True
