version: '3.1'
services:
  pgdb:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo18
    secrets:
      - postgresql_password

secrets:
  postgresql_password:
    file: odoo_pg_pass
    # the odoo_pg_pass is simply a file in the same directory with the password in it and nothing else
