name: Docker Compose Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-24.04

    env:
      ODOO_ADMIN_PASSWD: ${{ secrets.ODOO_ADMIN_PASSWD }}
      ODOO_DB_HOST: ${{ secrets.ODOO_DB_HOST }}
      ODOO_DB_PORT: ${{ secrets.ODOO_DB_PORT }}
      ODOO_DB_USER: ${{ secrets.ODOO_DB_USER }}
      ODOO_DB_PASSWORD: ${{ secrets.ODOO_DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install wkhtmltopdf
        run: |
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6.1-3.jammy_amd64.deb || sudo apt-get -f install -y
          
            - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xfonts-75dpi \
            python3-dev \
            build-essential \
            libjpeg-dev \
            libpq-dev \
            libjpeg8-dev \
            libxml2-dev \
            libssl-dev \
            libffi-dev \
            libmysqlclient-dev \
            libxslt1-dev \
            zlib1g-dev \
            libsasl2-dev \
            libldap2-dev \
            liblcms2-dev

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker containers
        run: docker-compose -f docker/docker-compose.yml up -d

      - name: Wait for services to be ready (optional)
        run: sleep 15

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run pytest

      - name: Shut down Docker containers
        if: always()
        run: docker-compose -f docker/docker-compose.yml down
